title: Anthony Meyer # your name (or website title) here
logo: "/images/BSSM 2 Badge (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly analytical and detail-oriented data scientist who knows SQL and Python.  
  Has a deep level of understanding of mathematics including but not limited to linear algebra and multivariable calculus.  
  <br><br>
  Skilled in  data analysis and visualization, and familiar with machine learning algorithms such as linear and logistic regression, k nearest neighbors, decision trees and random forests, and deep neural nets.  
  Excellent written and oral communication skills built from teaching college level mathematics to non-math majors and working one-on-one with life coaching clients. 
  <br><br>
  <a href="www.linkedin.com/in/anthony-j-meyer">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
