title: Anthony Meyer # your name (or website title) here
logo: "/images/BSSM 2 Badge (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly analytical and detail-oriented mathematician with in-depth knowledge of Python programming language.  
  Has a deep level of understanding of mathematics including but not limited to linear algebra, statistics, and multivariable calculus.  
  Currently enrolled in an online course in data science and machine learning developing tools for data analysis and visualization, and machine learning algorithms.  
  Excellent written and oral communication skills built from teaching college level mathematics to non-math majors and working one-on-one with life coaching clients. 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/anthony-j-meyer">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
